language: java

jdk:
- oraclejdk7

before_install:
  - chmod +x ./.travis/artifact-upload.sh
  - chmod +x ./.travis/maven-build.shs

script: ./.travis/maven-build.sh

notifications:
  slack:
    secure: ciAOsdv9lf/IbAwyzeR/z2nlBSevmBHBqca6tf0Yh2DIyAx/uUo1ojon0W7Kv6tCECGhSTdfQAnZ+nFjjqaRs+Jq4svd9WKYrFuZyOWmT31iSJ/nvPymRvevSsgwpSKr0nJS9dxePKto/T3ozW29kx88eaJQH17zOaX2rfuIje4=
  webhooks:
    urls:
      - https://dockbit.com/webhooks/7PrMKazLtLw5hhpXvakVKWoq
    on_success: always
    on_failure: always
    on_start: never

addons:
  artifacts: true
    s3_region: "us-west-1"

cache:
  directories:
  - .autoconf
  - $HOME/.m2
